const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What would you like to watch today?",
    home: "Home",
    login: "Login",
    logout: "Logout",
    profile: "Profile",
    settings: "Settings",
    welcome: "Welcome",
    movies: "Movies",
    nowPlaying: "Now Playing",
    popular: "Popular",
    upcoming: "Upcoming",
    noResults: "No results found",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    home: "होम",
    login: "लॉगिन",
    logout: "लॉगआउट",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    welcome: "स्वागत है",
    movies: "फ़िल्में",
    nowPlaying: "अभी चल रही हैं",
    popular: "लोकप्रिय",
    upcoming: "आने वाली फ़िल्में",
    noResults: "कोई परिणाम नहीं मिला",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    home: "Inicio",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    profile: "Perfil",
    settings: "Configuración",
    welcome: "Bienvenido",
    movies: "Películas",
    nowPlaying: "En cartelera",
    popular: "Populares",
    upcoming: "Próximamente",
  },
};

export default lang;
